/*
 * Copyright (C) 2016+     AzerothCore <www.azerothcore.org>, released under GNU GPL v2 license: https://github.com/azerothcore/azerothcore-wotlk/blob/master/LICENSE-GPL2
 * Copyright (C) 2008-2016 TrinityCore <http://www.trinitycore.org/>
 * Copyright (C) 2005-2009 MaNGOS <http://getmangos.com/>
 */

#ifndef TRINITY_DBCSFRM_H
#define TRINITY_DBCSFRM_H

AC_GAME_API char const Achievementfmt[] = "niixssssssssssssssssxxxxxxxxxxxxxxxxxxiixixxxxxxxxxxxxxxxxxxii";
AC_GAME_API const std::string CustomAchievementfmt="pppaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaapapaaaaaaaaaaaaaaaaaapp";
AC_GAME_API const std::string CustomAchievementIndex = "ID";
AC_GAME_API char const AchievementCategoryfmt[] = "nixxxxxxxxxxxxxxxxxx";
AC_GAME_API char const AchievementCriteriafmt[] = "niiiiiiiixxxxxxxxxxxxxxxxxiiiix";
AC_GAME_API char const AreaTableEntryfmt[] = "niiiixxxxxissssssssssssssssxiiiiixxx";
AC_GAME_API char const AreaGroupEntryfmt[] = "niiiiiii";
AC_GAME_API char const AreaPOIEntryfmt[] = "niiiiiiiiiiifffixixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxix";
AC_GAME_API char const AuctionHouseEntryfmt[] = "niiixxxxxxxxxxxxxxxxx";
AC_GAME_API char const BankBagSlotPricesEntryfmt[] = "ni";
AC_GAME_API char const BarberShopStyleEntryfmt[] = "nixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxiii";
AC_GAME_API char const BattlemasterListEntryfmt[] = "niiiiiiiiixssssssssssssssssxiixx";
AC_GAME_API char const CharStartOutfitEntryfmt[] = "dbbbXiiiiiiiiiiiiiiiiiiiiiiiixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
AC_GAME_API char const CharTitlesEntryfmt[] = "nxssssssssssssssssxssssssssssssssssxi";
AC_GAME_API char const ChatChannelsEntryfmt[] = "nixssssssssssssssssxxxxxxxxxxxxxxxxxx"; // ChatChannelsEntryfmt, index not used (more compact store)
AC_GAME_API char const ChrClassesEntryfmt[] = "nxixssssssssssssssssxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxixii";
AC_GAME_API char const ChrRacesEntryfmt[] = "nxixiixixxxxixssssssssssssssssxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxi";
AC_GAME_API char const CinematicSequencesEntryfmt[] = "nxxxxxxxxx";
AC_GAME_API char const CreatureDisplayInfofmt[] = "nixxfxxxxxxxxxxx";
AC_GAME_API char const CreatureFamilyfmt[] = "nfifiiiiixssssssssssssssssxx";
AC_GAME_API char const CreatureModelDatafmt[] = "nxxxfxxxxxxxxxxffxxxxxxxxxxx";
AC_GAME_API char const CreatureSpellDatafmt[] = "niiiixxxx";
AC_GAME_API char const CreatureTypefmt[] = "nxxxxxxxxxxxxxxxxxx";
AC_GAME_API char const CurrencyTypesfmt[] = "xnxi";
AC_GAME_API char const DestructibleModelDatafmt[] = "nxxixxxixxxixxxixxx";
AC_GAME_API char const DungeonEncounterfmt[] = "niixissssssssssssssssxx";
AC_GAME_API char const DurabilityCostsfmt[] = "niiiiiiiiiiiiiiiiiiiiiiiiiiiii";
AC_GAME_API char const DurabilityQualityfmt[] = "nf";
AC_GAME_API char const EmotesEntryfmt[] = "nxxiiix";
AC_GAME_API char const EmotesTextEntryfmt[] = "nxixxxxxxxxxxxxxxxx";
AC_GAME_API char const FactionEntryfmt[] = "niiiiiiiiiiiiiiiiiiffixssssssssssssssssxxxxxxxxxxxxxxxxxx";
AC_GAME_API char const FactionTemplateEntryfmt[] = "niiiiiiiiiiiii";
AC_GAME_API char const GameObjectDisplayInfofmt[] = "nsxxxxxxxxxxffffffx";
AC_GAME_API char const GemPropertiesEntryfmt[] = "nixxi";
AC_GAME_API char const GlyphPropertiesfmt[] = "niii";
AC_GAME_API char const GlyphSlotfmt[] = "nii";
AC_GAME_API char const GtBarberShopCostBasefmt[] = "f";
AC_GAME_API char const GtCombatRatingsfmt[] = "f";
AC_GAME_API char const GtChanceToMeleeCritBasefmt[] = "f";
AC_GAME_API char const GtChanceToMeleeCritfmt[] = "f";
AC_GAME_API char const GtChanceToSpellCritBasefmt[] = "f";
AC_GAME_API char const GtChanceToSpellCritfmt[] = "f";
AC_GAME_API char const GtNPCManaCostScalerfmt[] = "f";
AC_GAME_API char const GtOCTClassCombatRatingScalarfmt[] = "df";
AC_GAME_API char const GtOCTRegenHPfmt[] = "f";
// AC_GAME_API char const GtOCTRegenMPfmt[] = "f";
AC_GAME_API char const GtRegenHPPerSptfmt[] = "f";
AC_GAME_API char const GtRegenMPPerSptfmt[] = "f";
AC_GAME_API char const Holidaysfmt[] = "niiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiixxsiix";
AC_GAME_API char const ItemBagFamilyfmt[] = "nxxxxxxxxxxxxxxxxx";
AC_GAME_API char const ItemDisplayTemplateEntryfmt[] = "nxxxxsxxxxxxxxxxxxxxxxxxx";
//AC_GAME_API char const ItemCondExtCostsEntryfmt[] = "xiii";
AC_GAME_API char const ItemExtendedCostEntryfmt[] = "niiiiiiiiiiiiiix";
AC_GAME_API char const ItemLimitCategoryEntryfmt[] = "nxxxxxxxxxxxxxxxxxii";
AC_GAME_API char const ItemRandomPropertiesfmt[] = "nxiiixxssssssssssssssssx";
AC_GAME_API char const ItemRandomSuffixfmt[] = "nssssssssssssssssxxiiixxiiixx";
AC_GAME_API char const ItemSetEntryfmt[] = "dssssssssssssssssxiiiiiiiiiixxxxxxxiiiiiiiiiiiiiiiiii";
AC_GAME_API char const LFGDungeonEntryfmt[] = "nssssssssssssssssxiiiiiiiiixxixixxxxxxxxxxxxxxxxx";
AC_GAME_API char const LightEntryfmt[] = "nifffxxxxxxxxxx";
AC_GAME_API char const LiquidTypefmt[] = "nxxixixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
AC_GAME_API char const LockEntryfmt[] = "niiiiiiiiiiiiiiiiiiiiiiiixxxxxxxx";
AC_GAME_API char const MailTemplateEntryfmt[] = "nxxxxxxxxxxxxxxxxxssssssssssssssssx";
AC_GAME_API char const MapEntryfmt[] = "nxiixssssssssssssssssxixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxixiffxiii";
AC_GAME_API char const MapDifficultyEntryfmt[] = "diisxxxxxxxxxxxxxxxxiix";
AC_GAME_API char const MovieEntryfmt[] = "nxx";
AC_GAME_API char const OverrideSpellDatafmt[] = "niiiiiiiiiix";
AC_GAME_API char const PowerDisplayfmt[] = "nixxxx";
AC_GAME_API char const QuestSortEntryfmt[] = "nxxxxxxxxxxxxxxxxx";
AC_GAME_API char const QuestXPfmt[] = "niiiiiiiiii";
AC_GAME_API char const QuestFactionRewardfmt[] = "niiiiiiiiii";
AC_GAME_API char const PvPDifficultyfmt[] = "diiiii";
AC_GAME_API char const RandomPropertiesPointsfmt[] = "niiiiiiiiiiiiiii";
AC_GAME_API char const ScalingStatDistributionfmt[] = "niiiiiiiiiiiiiiiiiiiii";
AC_GAME_API char const ScalingStatValuesfmt[] = "iniiiiiiiiiiiiiiiiiiiiii";
AC_GAME_API char const SkillLinefmt[] = "nixssssssssssssssssxxxxxxxxxxxxxxxxxxixxxxxxxxxxxxxxxxxi";
AC_GAME_API char const SkillLineAbilityfmt[] = "niiiixxiiiiixx";
AC_GAME_API char const SoundEntriesfmt[] = "nxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
AC_GAME_API char const SpellCastTimefmt[] = "nixx";
AC_GAME_API char const SpellCategoryfmt[] = "ni";
AC_GAME_API char const SpellDifficultyfmt[] = "niiii";
AC_GAME_API const std::string CustomSpellDifficultyfmt="ppppp";
AC_GAME_API const std::string CustomSpellDifficultyIndex="id";
AC_GAME_API char const SpellDurationfmt[] = "niii";
AC_GAME_API char const SpellEntryfmt[] = "niiiiiiiiiiiixixiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiifxiiiiiiiiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiifffiiiiiiiiiiiiixssssssssssssssssxssssssssssssssssxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxiiiiiiiiiiixfffxxxiiiiixxfffxx";
AC_GAME_API const std::string CustomSpellEntryfmt = "papppppppppppapapaaaaaaaaaaapaaapapppppppaaaaapaapaaaaaaaaaaaaaaaaaappppppppppppppppppppppppppppppppppppaaappppppppppppaaapppppppppaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaappppppppapppaaaaappaaaaaaa";
AC_GAME_API const std::string CustomSpellEntryIndex = "Id";
AC_GAME_API char const SpellFocusObjectfmt[] = "nxxxxxxxxxxxxxxxxx";
AC_GAME_API char const SpellItemEnchantmentfmt[] = "niiiiiiixxxiiissssssssssssssssxiiiiiii";
AC_GAME_API char const SpellItemEnchantmentConditionfmt[] = "nbbbbbxxxxxbbbbbbbbbbiiiiiXXXXX";
AC_GAME_API char const SpellRadiusfmt[] = "nfff";
AC_GAME_API char const SpellRangefmt[] = "nffffixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
AC_GAME_API char const SpellRuneCostfmt[] = "niiii";
AC_GAME_API char const SpellShapeshiftfmt[] = "nxxxxxxxxxxxxxxxxxxiixiiixxiiiiiiii";
AC_GAME_API char const StableSlotPricesfmt[] = "ni";
AC_GAME_API char const SummonPropertiesfmt[] = "niiiii";
AC_GAME_API char const TalentEntryfmt[] = "niiiiiiiixxxxixxixxixxx";
AC_GAME_API char const TalentTabEntryfmt[] = "nxxxxxxxxxxxxxxxxxxxiiix";
AC_GAME_API char const TaxiNodesEntryfmt[] = "nifffssssssssssssssssxii";
AC_GAME_API char const TaxiPathEntryfmt[] = "niii";
AC_GAME_API char const TaxiPathNodeEntryfmt[] = "diiifffiiii";
AC_GAME_API char const TeamContributionPointsfmt[] = "df";
AC_GAME_API char const TotemCategoryEntryfmt[] = "nxxxxxxxxxxxxxxxxxii";
AC_GAME_API char const TransportAnimationfmt[] = "diifffx";
AC_GAME_API char const TransportRotationfmt[] = "diiffff";
AC_GAME_API char const VehicleEntryfmt[] = "niffffiiiiiiiifffffffffffffffssssfifiixx";
AC_GAME_API char const VehicleSeatEntryfmt[] = "niiffffffffffiiiiiifffffffiiifffiiiiiiiffiiiiixxxxxxxxxxxx";
AC_GAME_API char const WMOAreaTableEntryfmt[] = "niiixxxxxiixxxxxxxxxxxxxxxxx";
AC_GAME_API char const WorldMapAreaEntryfmt[] = "xinxffffixx";
AC_GAME_API char const WorldMapOverlayEntryfmt[] = "nxiiiixxxxxxxxxxx";

#endif
